### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by mmcbride1007** [smashwilson/merge-conflicts#254] opened 2016-11-16 13:30 UTC
Assigning custom properties to a marker when creating/copying it is
deprecated. Please consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71)
DisplayMarkerLayer.markBufferRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
TextEditor.markBufferRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1753:38)
ConflictVisitor.markSide (/Users/mcbridem/.atom/packages/merge-conflicts/lib/conflict.js:308:38)
ConflictVisitor.visitOurSide (/Users/mcbridem/.atom/packages/merge-conflicts/lib/conflict.js:264:27)
```

**Comment by pranshu1992** [comment] 2017-01-12 21:59
Assigning custom properties to a marker when creating/copying it is deprecated.   
Please, consider storing the custom properties you need in some other object in your package,   keyed by the marker's id property.  
```Function.extractParams - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markRange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71
DisplayMarkerLayer.markBufferRange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62
TextEditor.markBufferRange - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1753:38
ConflictVisitor.markSide - /Users/prkumar/.atom/packages/merge-conflicts/lib/conflict.js:308:38
ConflictVisitor.visitOurSide - /Users/prkumar/.atom/packages/merge-conflicts/lib/conflict.js:264:27```

**Comment by WaKeMaTTa** [comment] 2017-01-16 11:14
Assigning custom properties to a marker when creating/copying it is deprecated.
Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.

```
Function.extractParams - /opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markRange - /opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71
DisplayMarkerLayer.markBufferRange - /opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62
TextEditor.markBufferRange - /opt/atom/resources/app.asar/src/text-editor.js:1753:38
ConflictVisitor.markSide - /home/wakematta/.atom/packages/merge-conflicts/lib/conflict.js:308:38
ConflictVisitor.visitTheirSide - /home/wakematta/.atom/packages/merge-conflicts/lib/conflict.js:301:29
```

**Comment by ryanpatiency** [comment] 2017-03-04 09:06
same here

**Comment by smashwilson** [comment] 2017-05-16 19:22
Duplicate of #262.

**Closed by smashwilson** 2017-05-16 19:22 UTC
