### ISSUE TITLE
Clicking on Use me, doesn't solve the conflict. Both the code is still present in the page

### ISSUE THREAD

**Issue by ronakrrb** [smashwilson/merge-conflicts#121] opened 2015-02-01 06:52 UTC
![screen shot 2015-02-01 at 12 16 56 pm](https://cloud.githubusercontent.com/assets/5681924/5991323/edd76ab0-aa0c-11e4-8e05-8deedae5fa4e.png)

![screen shot 2015-02-01 at 12 20 34 pm](https://cloud.githubusercontent.com/assets/5681924/5991325/11019614-aa0d-11e4-8362-0f1f00139c1a.png)

The first image is the  before merging image and the second image is the after merging image

**Comment by erikdonohoo** [comment] 2015-02-02 18:49
Yep.  This package hasn't worked properly for a while now +1

**Comment by smashwilson** [comment] 2015-02-05 16:43
:unamused: Nuts.

I have a suspicion that #98 is the root cause here - the exception there is raised during conflict resolution, which prevents the unchosen conflict sides from deleting their marked lines properly. I don't suppose you see a stack trace in the console?

> Yep. This package hasn't worked properly for a while now +1

My apologies for that - an unfortunate consequence of having one primary contributor and sitting on top of a fast-evolving API. The good news is that I'm on more stable parts of the Atom API now. For a long time, I had to muck around with injecting DOM nodes into the EditorView and all kinds of other fragile things.

**Comment by smashwilson** [comment] 2015-02-05 16:47
Hmm, I can reproduce easily. No stack trace. Checking it out now.

**Comment by erikdonohoo** [comment] 2015-02-05 19:18
Hey @smashwilson .  No complaints.  I LOVE your package and the work you put into it.  Hopefully now that they announced 1.0 there shouldn't be as much breaking changes to deal with.  I hope you feel the love.  We love this package.

**Comment by smashwilson** [comment] 2015-02-05 19:27
> Hey @smashwilson . No complaints. I LOVE your package and the work you put into it. Hopefully now that they announced 1.0 there shouldn't be as much breaking changes to deal with. I hope you feel the love. We love this package.

Haha, thanks. I greatly appreciate everyone who reports these issues, too, by the way. Occasionally I have stretches of time where I'm most working on projects alone, which means fewer conflicts, which means that left to my own devices I wouldn't even notice that it was broken for a long time - so thanks to you and @ronakrrb for bringing this up!

Also, I think that I really need a better set of conflicts to test with - my artificial, trivial conflict sample isn't cutting it. The bugs I'm seeing now are related to scrolling or timing issues that only happen on "real" files.

I think that I've tracked this one down, by the way - I was wrong about it being premature marker destruction. Looks like I'm unsubscribing from events in a `detached` hook that's being called every time you scroll off-page, not just when I'm actually destroying the element! I should have a PR that fixes this up soon :mag: :footprints:

**Comment by erikdonohoo** [comment] 2015-02-06 03:42
@smashwilson Awesome.  Thank you!

**Comment by smashwilson** [comment] 2015-04-11 17:53
I'll close this for now, since I'm pretty sure I found this specific issue - re-open (or open new issues) if you see anything like this again. :bow:

**Closed by smashwilson** 2015-04-11 17:53 UTC
