### ISSUE TITLE
Headers break out of the file's pane

### ISSUE THREAD

**Issue by kevinansfield** [smashwilson/merge-conflicts#251] opened 2016-09-27 10:14 UTC
When using multiple panes the diff headers break out of the diff's pane and the action buttons end up sitting on top of an unrelated pane.

![screen shot 2016-09-27 at 11 10 43](https://cloud.githubusercontent.com/assets/415/18869201/2d9701de-84a3-11e6-9e76-c059664b339a.png)

Atom: 1.10.2
UI Theme: One Dark
merge-conflicts: 1.4.4

**Comment by thisolivier** [comment] 2016-12-15 17:38
I can confirm the same issue with different themes.

![screen shot 2016-12-15 at 17 37 16](https://cloud.githubusercontent.com/assets/3058656/21235093/413d69f2-c2ed-11e6-90dc-5ab965cacc43.png)

Atom 1.12.7
UI Theme: Seti UI
Syntax Theme: Fictus Light

**Comment by smashwilson** [comment] 2017-05-16 19:24
Duplicate of #256, and this repository is being [deprecated](https://github.com/smashwilson/merge-conflicts/blob/master/docs/announcement.md), so I won't be getting to this one here.

It should be taken care of by the [new git and GitHub package for Atom](https://github.com/atom/github). If you see something similar, please [file an issue there](https://github.com/atom/github/issues/new) to let us know. Thanks 🙇

**Closed by smashwilson** 2017-05-16 19:24 UTC
