### ISSUE TITLE
No conflicts detected.

### ISSUE THREAD

**Issue by nobleach** [smashwilson/merge-conflicts#263] opened 2017-03-14 00:38 UTC
I'm not even sure how to start troubleshooting this one:

<img width="946" alt="screenshot 2017-03-13 18 18 50" src="https://cloud.githubusercontent.com/assets/217134/23880825/e6815fe0-081b-11e7-8e34-d092bfa63631.png">

I've tried changing the theme just in case. (I did notice this wasn't working with the SETI theme, so I figured changing to the default theme was worth a shot)

This file does indeed have standard diff markers. It's the first file I've ever tried with this tool, so I can't just try another conflicted file at the moment. I was just wondering if there were things I could check.

**Comment by smashwilson** [comment] 2017-03-14 00:51
This looks like a duplicate of #243. Can you confirm your version of merge-conflicts, and provide the output of running `git status --porcelain` on the command line?

**Comment by nobleach** [comment] 2017-03-14 00:55
merge-conflicts version: 1.4.4
Atom version: 1.15.0

`git status --porcelain` returns no output.

**Comment by smashwilson** [comment] 2017-03-14 00:59
Ah, if `git status --porcelain` has no output, then git itself doesn't think that this file contains conflicts. (This package uses the git index to determine that a merge is in progress, not the contents of the file. `git status` will list the file as "modified by both" and `git status --porcelain` will list its path with a prefix like `UU`.)

How did you get these conflict markers? Were they accidentally committed from a previous merge?

**Comment by nobleach** [comment] 2017-03-14 01:01
It's very possible that I resolved all but one file, then committed most of the resolved files. That would make sense.

**Closed** 2017-03-14 01:07 UTC
