### ISSUE TITLE
Code editor overlay

### ISSUE THREAD

**Issue by tn** [smashwilson/merge-conflicts#226] opened 2016-04-18 09:56 UTC
Theme & syntax: one light

<img width="482" alt="screen shot 2016-04-18 at 12 52 06" src="https://cloud.githubusercontent.com/assets/6479637/14600361/d270062e-0564-11e6-8d6a-9cff433d35fe.png">

**Comment by smashwilson** [comment] 2016-04-25 19:05
This is a duplicate of #188. Please subscribe there for updates. :bow:

**Closed by smashwilson** 2016-04-25 19:05 UTC
