### ISSUE TITLE
Breaks when used with atom-editorconfig

### ISSUE THREAD

**Issue by simon-ls** [smashwilson/merge-conflicts#212] opened 2016-03-14 17:56 UTC
The conflict highlighting (and all functionality dependant upon this) does not work when the atom-editorconfig plugin is enabled. 

Instead, git's default breaks are shown.

**Comment by smashwilson** [comment] 2016-03-15 00:35
Duplicate of sindresorhus/atom-editorconfig#65 and #196. Please subscribe to those issues instead for updates.

**Closed by smashwilson** 2016-03-15 00:35 UTC
