### ISSUE TITLE
In conflict resolution, branch name get over the rest if the UI.

### ISSUE THREAD

**Issue by Succo** [smashwilson/merge-conflicts#209] opened 2016-02-24 23:44 UTC
When you have the part of your UI where branch name are come over other panels when those panel are over text with merge issue.

I think the attached file illustrate it better than me.

<img width="1493" alt="screen shot 2016-02-24 at 6 39 38 pm" src="https://cloud.githubusercontent.com/assets/8531875/13305045/89fc0bda-db26-11e5-8612-7c4343021028.png">

**Comment by rajashekar007** [comment] 2016-03-04 09:35
Yes, I came here to report the same thing. :+1:

**Comment by rajashekar007** [comment] 2016-03-04 09:41
#188 covers this, duplicate bug.

**Comment by smashwilson** [comment] 2016-04-25 19:04
Yup, this is a duplicate of #188; please subscribe there for updates.

**Closed by smashwilson** 2016-04-25 19:04 UTC
