### ISSUE TITLE
Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

### ISSUE THREAD

**Issue by ToxEn** [smashwilson/merge-conflicts#211] opened 2016-03-06 15:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

```
At /Users/duncanroze/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189

Error: The index is locked. This might be due to a concurrent or crashed process
    at Error (native)
    at Function.GitBridge.add (/Users/duncanroze/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189:15)
    at ResolverView.resolve (/Users/duncanroze/.atom/packages/merge-conflicts/lib/view/resolver-view.coffee:61:15)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:59.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -3:57.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -3:49.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:31.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:30.1.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:29.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -3:29.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:24.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:23.2.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -3:22.6.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:22.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:21.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -3:10.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 70x -3:09.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:31.2.0 core:save (atom-text-editor.editor.mini.is-focused)
  3x -1:55.1.0 merge-conflicts:detect (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icons"
    ],
    "themes": [
      "atom-storm-ui",
      "one-dark-syntax"
    ]
  },
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-storm-ui, v2.0.1
auto-indent, v0.5.0
color-picker, v2.1.1
language-javascript-jsx, v0.3.7
merge-conflicts, v1.3.7
pigments, v0.24.2

# Dev
No dev packages
```

**Comment by rgbkrk** [comment] 2016-03-14 02:22
Ran into this just now while using `git cherry-pick`.

**Comment by MoOx** [comment] 2016-03-14 14:36
same. I started a rebase from cli, and continue from atom, then after having choose their changes, I clicked on the modal "Stage" button, and boom.

**Comment by ToxEn** [comment] 2016-03-14 20:24
Yes, it's just weird, i just spam this stage button, and few moments later, it works !

**Comment by smashwilson** [comment] 2016-03-15 00:28
This is a duplicate of #171 which has been confounding me for a long time, now.

**Closed by smashwilson** 2016-03-15 00:28 UTC
